// File: Async.idl
// Copyright (c) Microsoft Corporation.  All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Classes Reference and related electronic
// documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft C++ Libraries products.

#include <olectl.h>
// Async.idl : IDL source for Async.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Async.tlb) and marshalling code.

	[
		object,
		uuid(665F78E1-81B2-46F9-B9B3-6AE3B89F0B0E),
		dual,
		helpstring("IWarIncLauncher Interface"),
		pointer_default(unique)
	]
	interface IWarIncLaunch : IDispatch
	{
		import "oaidl.idl";
		import "ocidl.idl";

		[propput, id(0)] HRESULT cmdLine([in]BSTR cmdLine);
		[propget, id(0)] HRESULT cmdLine([out,retval]BSTR* cmdLine);

	};
[
	uuid(66A27650-1B12-4431-A9C1-ECA3EFD1CC1C),
	version(1.0),
	helpstring("WarIncLauncher 1.0 Type Library")
]
library WarIncLib
{
	importlib("stdole32.tlb");
	

	[
		uuid(64F2ECD6-505E-4A9A-9606-4727B70DF3E9),
		helpstring("WarIncLauncher Class")
	]
	coclass CWarIncLaunch
	{
		[default] interface IWarIncLaunch;
	};
};
